config/routes.rb
Rails.application.routes.draw do
  resources :rides

  resources :tweets

  resources :posts

  resources :searches do
    member do
      post 'default'
    end
  end

  resources :resorts

  root to: 'searches#new'
  match 'rides/query' => 'rides#query', :as => :rides_query, via: [:get, :post]
  get "/about" => "resorts#about"

end

app/models/search.rb
class Search
  include ActiveModel::Model
  validates :location, presence: true

  attr_accessor :location
  def geolocater
    GeoLocate.new(location)
  end

  def resorts
    @resorts ||= geolocater.locate
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
    @search = Search.new
  end

  def self.default
    @search = Search.new(['110 ski Hill rd, Breckenridge'])
    @resorts = @search.resorts
    render action: 'show'
  end

  def create
    @search = Search.new(params[:search])
    @location = @search.location
    @resorts = @search.resorts
    render action: 'show'
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
<% if @search.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@search.errors.count, "error") %>
    prohibited this search from being saved:
  </h2>

  <ul>
    <% @search.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div onclick="getLocation()" class="submit" style="font-size: 3em !important;line-height: 1em !important;">Find Me</div>

<p id="feedback"></p>

<div class="actions">
  <div class="field">
    <%= f.label :location,  style:'margin: auto;' %><br/>
    <%= f.text_field :location, {:class => 'textfield', style:'border-radius: 5px;'} %>
  </div>
  <%= f.submit 'Submit', {class: 'submit', style: "font-size: 3em !important;line-height: 1.4em !important;"} %>
</div>
<% end %>
<script>
  var x = document.getElementById('search_location');
  var y = document.getElementById('feedback');
  function getLocation() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(showPosition);
      y.innerHTML = "Searching For Your Location...";
    } else {
      x.innerHTML = "Geolocation is not supported by this browser.";
    }

  }

  function showPosition(position) {
    x.value = position.coords.latitude + ", " + position.coords.longitude;
    y.innerHTML = "Your Location Found";
  }
</script>

app/views/searches/_formnewride.html.erb
<%= form_for(@ride) do |f| %>
<% if @ride.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@search.errors.count, "error") %>
    prohibited this search from being saved:
  </h2>

  <ul>
    <% @ride.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="actions">
  <div class="field">
    <%= f.label :location_from %><br/>
    <%= f.text_field :location_from, :class => 'textfield' %>
    <%= f.label :resort_to %><br/>
    <%= f.text_field :resort_to, :class => 'textfield' %>
  </div>
  <%= f.submit 'Submit', :class => 'submit' %>
</div>
<% end %>

app/views/searches/_formshow.html.erb
<%= form_for(@search) do |f| %>
<div class="row">
  <% if @search.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@search.errors.count, "error") %>
      prohibited this search from being saved:</h2>

    <ul>
      <% @search.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="actions" style="padding: 20px;margin-bottom: 40px">
    <div class="col-xs-6">
      <%= f.text_field :location, :class => 'submitfield', :style => 'min-width: 100%; max-height: 32px' %>

    </div>
    <div class="col-xs-6">
      <%= f.submit 'Submit', :class => 'submit'%>
    </div>
  </div>

</div>

</div>
</div>
</div>
<% end %>

app/views/searches/_table.html.erb
<table class="table" style="padding-left: 0%; padding-right: 0%; font-family:"Verdana"";>
  <thead>
    <th class="header" style="border-width: 0;">Name</th>
    <th class="header" style="border-width: 0;">Distance</th>
    <th class="header" style="border-width: 0;">Temp</th>
    <th class="header" style="border-width: 0;">Base</th>
    <th class="header" style="border-width: 0;">Snowfall</th>
    <!-- <th>Rides</th> -->
    <!-- <th>Webcam</th> -->
  </thead>
  <tbody>
    <%- @resorts.each do |resort| %>
    <tr>
      <td class="" ><%= link_to resort.name, resort_path(resort.id, :location => @location),style: "font-size: 1.1em;" %></td>
      <td class="" style="text-align: center;"><%= resort.distance_text %></td>
      <td class="" style="text-align: center;"><%= resort.temp  %>
        &deg; F</td>
      <td class="" style="text-align: center;"><%= resort.base  %>
        "</td>
      <td class="" style="text-align: center;"><%= resort.snowfall  %>
        "</td>
      <!-- <td class="resort_stats"><%= link_to Ride.where(resort_to: resort.name).count, rides_path(resort_to: resort.name) %></td> -->

      <!-- <td><%- resort.webcam.split(",").each_with_index do |webc, i| %>
        <a data-featherlight="image" href="<%= webc %>">Camera:
          <%=i+1%></a>
        <br>
        <%- end %>
      </td> -->
    </tf>
  </tr>

  <%- end %>
</tbody>
<script src="//code.jquery.com/jquery-latest.js"></script>
<script charset="utf-8" src="//cdn.rawgit.com/noelboss/featherlight/master/release/featherlight.min.js" type="text/javascript"></script>

</table>

app/views/searches/edit.html.erb
<h1>Editing search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %>
|
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<div style="background-color: transparent">

<h1>Listing searches</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @searches.each do |search| %>
    <tr>
      <td><%= link_to 'Show', search %></td>
      <td><%= link_to 'Edit', edit_search_path(search) %></td>
      <td><%= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<!DOCTYPE html>
<html xml:lang="en" lang="en" class="htmlnew">


<div class="res_nav boxy" style="z-index: 3; padding: 15px; background-color: transparent;">
  <div class="col-xs-6">
    <a href="/"><img src="assets/logo1.svg" style="height: 100px;" alt="Kiwi standing on oval"></a>

</object>
</a></h1>
</div>
<div class="col-xs-6">

<div class="row" >
  <h3  style="margin-top: 15px; color: white;text-align: right;font-size: 30px;font-family: 'Rough';"><%= link_to "Resorts", resorts_path, style: "color: white;text-align: right;" %></h3>
</div>
<div class="row" >

  <h3  style="margin: 0px;color: white;text-align: right; font-size: 30px;font-family: 'Rough';"><%= link_to "About", about_path, style: "color: white;text-align: right;" %></h3>
</div>
</div>


</div>

<div id="background">
<!--
  <div class="centered">

  </div> -->
</div>

<div style="width: 100%;padding: 0px;background-color: transparent;position: fixed ;bottom: 38px;left: 0px;"class="container-fluid">
<div class="boxy" style="padding: 0px;" >
      <div class="row " style="padding: 15px;">

      <div class="col-xs-8 "style="z-index: 2; ">
        <h1 style="font-size: 7em;color: white; text-align: center;">Find Me Gnar</h1>
        <hr>
        <h2 style="color: #333; float: center; text-align: center;">
          Enter your location to find the best snow around
        </h2>


      </div>
      <div class="col-xs-4 boxy" style="max-height:300px; background-color: transparent">
        <%= render 'form' %>
      </div>
    </div>

    <!-- <div class="col-xs-4 box mid">

      <div class="boxy">

        <h1>Ride Share</h1>
        <p>
          Enter your location and destination to look for a ride
        </p>
        <%= render 'rides/form' %>
      </div>

    </div> -->

    </div>
</div>

</html>

app/views/searches/show.html.erb
<html class="htmlshow">

<div class="res_nav boxy" style="z-index: 3; padding: 15px;">
  <div class="col-xs-6">
    <a href="/"><img src="assets/logo2.svg" style="height: 100px;" alt="Kiwi standing on oval"></a>
</div>
<div class="col-xs-6">

<div class="row" style="margin: 0;">
  <h3  style="margin: 0px;float: right;font-size: 30px;font-family: 'Rough';"><%= link_to "Resorts", resorts_path %></h3>
</div>
<div class="row" style="margin: 0;">

  <h3  style="margin: 0px;float: right; font-size: 30px;font-family: 'Rough';"><%= link_to "About", about_path %></h3>
</div>
</div>


</div>
<!-- Wrap all page content here -->
<div style="width: 80%;margin: auto; padding-top: 80px;"class="container-fluid boxy">

    <div class="container-fluid">
      <%= render 'table' %>
      <%= render 'formshow' %>
    </div>
    <br>
    </div>

  </div>

</html>